package org.races.dao;
public class Dao_Constants {

String INSERT_DATA_CUSTOMER =  
	"INSERT INTO CUSTOMERDETAILS(CUSTOMERID,CUSTOMERDETAILS,CHASISNUMBER,ENGINENUMBER,DATEOFSALE,INSTALLATION) VALUES(?,?,?,?,?,?)";

String INSERT_SPARES_DETAILS = 
	"INSERT INTO SPARE_PARTS_DETAILS(SPARE_CODE,PART_DESCRIPTION,OBSOLETE,COST,MIN_ORDER) VALUES(?,?,?,?,?)";

String INSERT_DATA_SERVICE =  
"INSERT INTO SERVICEDETAILS(CHASISNUMBER,SERVICENAME,SERVICEDATE,JOBCARDNO,HOURS,COSTCHARGED) VALUES(?,?,?,?,?,?)";

String UPDATE_INSTALLATION_DATE = 
	"UPDATE CUSTOMERDETAILS SET INSTALLATION = ? WHERE CHASISNUMBER = ?";


String INSERT_SERVICE_SCHEDULE =  
"INSERT INTO SERVICESCHEDULE(SERVICENAME,MINDAYS,MAXDAYS,MINHOURS,MAXHOURS,COST) VALUES(?,?,?,?,?,?)";

String  INSERT_SERVICE_ACTUAL = "INSERT INTO CUSTOMER_VEHICLE_ACTUALS(chasisNumber,firstServicedate,firstServiceHours,secondServiceDate,secondServiceHours,thirdServiceDate,thirdServiceHours,fourthServiceDate,fourthServiceHours,fifthServiceDate,fifthServiceHours,sixthServiceDate,sixthServiceHours,seventhServiceDate,seventhServiceHours,eigthServiceDate,eigthServicehours,installationDate) VALUES (?,DATE_ADD(?,INTERVAL 30 DAY),100,DATE_ADD(?,INTERVAL 120 DAY),350,DATE_ADD(?,INTERVAL 210 DAY),600,DATE_ADD(?,INTERVAL 300 DAY),850,DATE_ADD(?,INTERVAL 390 DAY),1100,DATE_ADD(?,INTERVAL 480 DAY),1350,DATE_ADD(?,INTERVAL 570 DAY),1600,DATE_ADD(?,INTERVAL 660 DAY),1850,DATE_ADD(?,INTERVAL 2 DAY))"; 
//String INSERT_SERVICE_ACTUAL =  
//"INSERT INTO CUSTOMER_VEHICLE_ACTUALS(CHASISNUMBER,FIRSTSERVICEDATE,FIRSTSERVICEHOURS,SECONDSERVICEDATE,SECONDSERVICEHOURS,THIRDSERVICEDATE,THIRDSERVICEHOURS,FOURTHSERVICEDATE,FOURTHSERVICEHOURS,FIFTHSERVICEDATE,FIFTHSERVICEHOURS,SIXTHSERVICEDATE,SIXTHSERVICEHOURS,SEVENTHSERVICEDATE,SEVENTHSERVICEHOURS,EIGTHSERVICEDATE,EIGTHSERVICEHOURS,INSTALLATIONDATE) " +
//"VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

String  SELECT_SERVICE_ACTUAL = "SELECT * FROM CUSTOMER_VEHICLE_ACTUALS";
String  SELECT_DATA_SERVICE = "SELECT * FROM SERVICEDETAILS";
String  SELECT_DATA_CUSTOMER = "SELECT * FROM CUSTOMERDETAILS";
String  SELECT_SERVICE_SCHEDULE = "SELECT * FROM SERVICESCHEDULE";

String DELETE_DATA_CUSTOMER = "DELETE FROM CUSTOMERDETAILS";
String DELETE_DATA_SERVICE = "DELETE FROM SERVICEDETAILS";

//String SELECT_SERVICE_BY_MONTH = "select * from customer_vehicle_actuals where (EXTRACT(MONTH FROM firstServicedate) = EXTRACT(MONTH FROM ?)) OR (EXTRACT(MONTH FROM secondServiceDate) = EXTRACT(MONTH FROM ?)) OR (EXTRACT(MONTH FROM thirdServiceDate) = EXTRACT(MONTH FROM ?)) OR (EXTRACT(MONTH FROM fourthServiceDate) = EXTRACT(MONTH FROM ?)) OR (EXTRACT(MONTH FROM fifthServiceDate) = EXTRACT(MONTH FROM ?)) OR (EXTRACT(MONTH FROM sixthServiceDate) = EXTRACT(MONTH FROM ?)) OR (EXTRACT(MONTH FROM seventhServiceDate) = EXTRACT(MONTH FROM ?)) OR (EXTRACT(MONTH FROM eigthServicehours) = EXTRACT(MONTH FROM ?))";

String SELECT_SERVICE_BY_CHASISNO = "SELECT * FROM SERVICEDETAILS WHERE CHASISNUMBER LIKE ?";

String SELECT_FIRST_SERVICE_BYDATE = "select chasisnumber from customer_vehicle_actuals where (EXTRACT(MONTH FROM firstServicedate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM firstServicedate) = EXTRACT(YEAR FROM ? ))";
String SELECT_SECOND_SERVICE_BYDATE = "select chasisnumber from customer_vehicle_actuals where (EXTRACT(MONTH FROM secondServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM secondServiceDate) = EXTRACT(YEAR FROM ? ))";
String SELECT_THIRD_SERVICE_BYDATE = "select chasisnumber from customer_vehicle_actuals where (EXTRACT(MONTH FROM thirdServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM thirdServiceDate) = EXTRACT(YEAR FROM ? ))";
String SELECT_FOURTH_SERVICE_BYDATE = "select chasisnumber from customer_vehicle_actuals where (EXTRACT(MONTH FROM fourthServiceDate) = EXTRACT(MONTH FROM ?) AND EXTRACT(YEAR FROM fourthServiceDate) = EXTRACT(YEAR FROM ? ))";
String SELECT_FIFTH_SERVICE_BYDATE = "select chasisnumber from customer_vehicle_actuals where (EXTRACT(MONTH FROM fifthServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM fifthServiceDate) = EXTRACT(YEAR FROM ? ))";
String SELECT_SIXTH_SERVICE_BYDATE = "select chasisnumber from customer_vehicle_actuals where (EXTRACT(MONTH FROM sixthServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM sixthServiceDate) = EXTRACT(YEAR FROM ? ))";
String SELECT_SEVENTH_SERVICE_BYDATE = "select chasisnumber from customer_vehicle_actuals where (EXTRACT(MONTH FROM seventhServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM seventhServiceDate) = EXTRACT(YEAR FROM ?))";
String SELECT_EIGTH_SERVICE_BYDATE = "select chasisnumber from customer_vehicle_actuals where (EXTRACT(MONTH FROM eigthServiceDate) = EXTRACT(MONTH FROM ?) AND EXTRACT(YEAR FROM eigthServiceDate) = EXTRACT(YEAR FROM ?))";



String SELECT_SERVICEDETAILS_BYNAME = "select ServiceName,ServiceDate,Jobcardno,Hours,chasisNumber from servicedetails where chasisNumber = ? and servicename = ? ";

String SELECT_SERVICEDETAILS_BYNAME1 = "select sd.ServiceName ServiceName,cva.firstServiceDate Actual_ServiceDate,sd.Jobcardno Jobcardno,sd.Hours Hours,sd.chasisNumber chasisNumber from servicedetails sd, customer_vehicle_actuals cva where sd.chasisNumber = cva.chasisNumber and sd.chasisNumber = ? and sd.servicename = '1st Service'";

String SELECT_ACTUAL_SERVICE_BY_MONTH = "select * from customer_vehicle_actuals where (EXTRACT(MONTH FROM firstServicedate) = EXTRACT(MONTH FROM ?) AND EXTRACT(YEAR FROM firstServicedate) = EXTRACT(YEAR FROM ? )) OR (EXTRACT(MONTH FROM secondServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM secondServiceDate) = EXTRACT(YEAR FROM ?)) OR (EXTRACT(MONTH FROM thirdServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM thirdServiceDate) = EXTRACT(YEAR FROM ? )) OR (EXTRACT(MONTH FROM fourthServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM fourthServiceDate) = EXTRACT(YEAR FROM ? )) OR (EXTRACT(MONTH FROM fifthServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM fifthServiceDate) = EXTRACT(YEAR FROM ? )) OR (EXTRACT(MONTH FROM sixthServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM sixthServiceDate) = EXTRACT(YEAR FROM ? )) OR (EXTRACT(MONTH FROM seventhServiceDate) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM seventhServiceDate) = EXTRACT(YEAR FROM ? )) OR (EXTRACT(MONTH FROM eigthServicehours) = EXTRACT(MONTH FROM ? ) AND EXTRACT(YEAR FROM eigthServicehours) = EXTRACT(YEAR FROM ? ))";

String SELECT_CUSTOMER_BY_CHASISNO = "SELECT * FROM CUSTOMERDETAILS WHERE CHASISNUMBER LIKE ?";
String SELECT_CUSTOMERDETAILS_BY_CHASISNO = "SELECT customerDetails FROM CUSTOMERDETAILS WHERE CHASISNUMBER LIKE ?";

/* Queries to get the pending services based on particular DURATION*/

String SELECT_SERVICE_PENDING_BYMONTH_FIRST = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.firstServicedate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS FROM customer_vehicle_actuals CVA,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.firstServicedate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM CVA.firstServicedate) BETWEEN ? AND ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '1st Service' AND EXTRACT(MONTH FROM ServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM ServiceDate) BETWEEN ? AND ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYMONTH_SECOND = "SELECT CVA.CHASISNUMBER AS CHASISNUMBER,CVA.secondServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.secondServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM CVA.secondServiceDate) BETWEEN ? AND ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '2nd Service' AND EXTRACT(MONTH FROM ServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM ServiceDate) BETWEEN ? AND ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYMONTH_THIRD = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.thirdServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.thirdServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM CVA.thirdServiceDate) BETWEEN ? AND ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '3rd Service' AND EXTRACT(MONTH FROM ServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM ServiceDate) BETWEEN ? AND ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYMONTH_FOURTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER, CVA.fourthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.fourthServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM CVA.fourthServiceDate) BETWEEN ? AND ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '4th Service' AND EXTRACT(MONTH FROM ServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM ServiceDate) BETWEEN ? AND ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYMONTH_FIFTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER, CVA.fifthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.fifthServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM CVA.fifthServiceDate) BETWEEN ? AND ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '5th Service' AND EXTRACT(MONTH FROM ServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM ServiceDate) BETWEEN ? AND ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYMONTH_SIXTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.sixthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.sixthServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM CVA.sixthServiceDate) BETWEEN ? AND ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '6th Service' AND EXTRACT(MONTH FROM ServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM ServiceDate) BETWEEN ? AND ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYMONTH_SEVENTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER, CVA.seventhServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.seventhServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM CVA.seventhServiceDate) BETWEEN ? AND ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '7th Service' AND EXTRACT(MONTH FROM ServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM ServiceDate) BETWEEN ? AND ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYMONTH_EIGTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER, CVA.eigthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.eigthServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM CVA.eigthServiceDate) BETWEEN ? AND ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '8th Service' AND EXTRACT(MONTH FROM ServiceDate) BETWEEN ? AND ? AND EXTRACT(YEAR FROM ServiceDate) BETWEEN ? AND ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";



/* Queries to get the pending services based on particular MONTH FOR particular SERVICE*/
String SELECT_SERVICE_PENDING_BYSELECTED_MONTH_FIRST = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.firstServicedate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'1st Service' AS SERVICE_NAME FROM customer_vehicle_actuals CVA,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.firstServicedate) = ? AND EXTRACT(YEAR FROM CVA.firstServicedate) = ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '1st Service' AND EXTRACT(MONTH FROM ServiceDate) = ? AND EXTRACT(YEAR FROM ServiceDate) = ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYSELECTED_MONTH_SECOND = "SELECT CVA.CHASISNUMBER AS CHASISNUMBER,CVA.secondServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'2nd Service' AS SERVICE_NAME  FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.secondServiceDate) = ? AND EXTRACT(YEAR FROM CVA.secondServiceDate) = ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '2nd Service' AND EXTRACT(MONTH FROM ServiceDate) = ? AND EXTRACT(YEAR FROM ServiceDate) = ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYSELECTED_MONTH_THIRD = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.thirdServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'3rd Service' AS SERVICE_NAME  FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.thirdServiceDate) = ? AND EXTRACT(YEAR FROM CVA.thirdServiceDate) = ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '3rd Service' AND EXTRACT(MONTH FROM ServiceDate) = ? AND EXTRACT(YEAR FROM ServiceDate) = ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYSELECTED_MONTH_FOURTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER, CVA.fourthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'4th Service' AS SERVICE_NAME  FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.fourthServiceDate) = ? AND EXTRACT(YEAR FROM CVA.fourthServiceDate) = ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '4th Service' AND EXTRACT(MONTH FROM ServiceDate) = ? AND EXTRACT(YEAR FROM ServiceDate) = ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYSELECTED_MONTH_FIFTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER, CVA.fifthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'5th Service' AS SERVICE_NAME  FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.fifthServiceDate) = ? AND EXTRACT(YEAR FROM CVA.fifthServiceDate) = ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '5th Service' AND EXTRACT(MONTH FROM ServiceDate) = ? AND EXTRACT(YEAR FROM ServiceDate) = ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYSELECTED_MONTH_SIXTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.sixthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'6th Service' AS SERVICE_NAME  FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.sixthServiceDate) = ? AND EXTRACT(YEAR FROM CVA.sixthServiceDate) = ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '6th Service' AND EXTRACT(MONTH FROM ServiceDate) = ? AND EXTRACT(YEAR FROM ServiceDate) = ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYSELECTED_MONTH_SEVENTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER, CVA.seventhServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'7th Service' AS SERVICE_NAME  FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.seventhServiceDate) = ? AND EXTRACT(YEAR FROM CVA.seventhServiceDate) = ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '7th Service' AND EXTRACT(MONTH FROM ServiceDate) = ? AND EXTRACT(YEAR FROM ServiceDate) = ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";
String SELECT_SERVICE_PENDING_BYSELECTED_MONTH_EIGTH = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER, CVA.eigthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'8th Service' AS SERVICE_NAME  FROM customer_vehicle_actuals CVA ,customerDetails CD WHERE EXTRACT(MONTH FROM CVA.eigthServiceDate) = ? AND EXTRACT(YEAR FROM CVA.eigthServiceDate) = ? AND CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '8th Service' AND EXTRACT(MONTH FROM ServiceDate) = ? AND EXTRACT(YEAR FROM ServiceDate) = ? ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";

/*Queries to get the pending services based on particular service*/
String SELECT_SERVICE_PENDING_FOR_FIRSTSERVICE = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.firstServicedate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'1st Service' AS SERVICE_NAME FROM customer_vehicle_actuals CVA,customerDetails CD WHERE  CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '1st Service' ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";  
String SELECT_SERVICE_PENDING_FOR_SECONDSERVICE = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.secondServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'2nd Service' AS SERVICE_NAME FROM customer_vehicle_actuals CVA,customerDetails CD WHERE  CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '2nd Service' ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";  
String SELECT_SERVICE_PENDING_FOR_THIRDSERVICE = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.thirdServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'3rd Service' AS SERVICE_NAME FROM customer_vehicle_actuals CVA,customerDetails CD WHERE  CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '3rd Service' ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";  
String SELECT_SERVICE_PENDING_FOR_FOURTHSERVICE = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.fourthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'4th Service' AS SERVICE_NAME FROM customer_vehicle_actuals CVA,customerDetails CD WHERE  CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '4th Service' ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";  
String SELECT_SERVICE_PENDING_FOR_FIFTHSERVICE = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.fifthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'5th Service' AS SERVICE_NAME FROM customer_vehicle_actuals CVA,customerDetails CD WHERE  CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '5th Service' ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";  
String SELECT_SERVICE_PENDING_FOR_SIXTHSERVICE = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.sixthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'6th Service' AS SERVICE_NAME FROM customer_vehicle_actuals CVA,customerDetails CD WHERE  CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '6th Service' ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";  
String SELECT_SERVICE_PENDING_FOR_SEVENTHSERVICE = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.seventhServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'7th Service' AS SERVICE_NAME FROM customer_vehicle_actuals CVA,customerDetails CD WHERE  CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '7th Service' ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";  
String SELECT_SERVICE_PENDING_FOR_EIGTHSERVICE = "SELECT  CVA.CHASISNUMBER AS CHASISNUMBER,CVA.eigthServiceDate AS SERVICE_DATE,CD.CUSTOMERDETAILS AS CUSTOMER_DETAILS,'8th Service' AS SERVICE_NAME FROM customer_vehicle_actuals CVA,customerDetails CD WHERE  CVA.CHASISNUMBER NOT IN ( SELECT CHASISNUMBER FROM servicedetails WHERE ServiceName = '8th Service' ) AND CVA.CHASISNUMBER = CD.CHASISNUMBER";  



String GET_LOGIN_DETAILS = 
			"SELECT * FROM LOGINDETAILS WHERE USERNAME = ? AND PASSWORD = ?";

String GET_EMAILID =
		"SELECT EMAIL_ID FROM LOGINDETAILS WHERE USERNAME = ?";


/* For Chart 

String GET_DURATION_COUNT_1ST_SERVICE = "select DATE_FORMAT(firstServicedate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals where firstServicedate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM firstServicedate) ORDER BY EXTRACT(YEAR_MONTH FROM firstServicedate) DESC";
String GET_DURATION_COUNT_2ND_SERVICE = "select DATE_FORMAT(secondServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals where secondServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM secondServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM secondServiceDate) DESC";
String GET_DURATION_COUNT_3RD_SERVICE = "select DATE_FORMAT(thirdServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals where thirdServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM thirdServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM thirdServiceDate) DESC";
String GET_DURATION_COUNT_4TH_SERVICE = "select DATE_FORMAT(fourthServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals where fourthServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM fourthServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM fourthServiceDate) DESC";
String GET_DURATION_COUNT_5TH_SERVICE = "select DATE_FORMAT(fifthServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals where fifthServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM fifthServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM fifthServiceDate) DESC";
String GET_DURATION_COUNT_6TH_SERVICE = "select DATE_FORMAT(sixthServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals where sixthServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM sixthServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM sixthServiceDate) DESC";
String GET_DURATION_COUNT_7TH_SERVICE = "select DATE_FORMAT(seventhServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals where seventhServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM seventhServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM seventhServiceDate) DESC";
String GET_DURATION_COUNT_8TH_SERVICE = "select DATE_FORMAT(eigthServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals where eigthServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM eigthServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM eigthServiceDate) DESC";
String GET_DURATION_COUNT_COMPLETED_SERVICE = "SELECT DATE_FORMAT(ServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT FROM servicedetails where ServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM ServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM ServiceDate) DESC";
*/



/* For Chart*/

String GET_DURATION_COUNT_1ST_SERVICE = "select DATE_FORMAT(firstServicedate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals1 where firstServicedate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM firstServicedate) ORDER BY EXTRACT(YEAR_MONTH FROM firstServicedate) DESC";
String GET_DURATION_COUNT_2ND_SERVICE = "select DATE_FORMAT(secondServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals1 where secondServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM secondServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM secondServiceDate) DESC";
String GET_DURATION_COUNT_3RD_SERVICE = "select DATE_FORMAT(thirdServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals1 where thirdServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM thirdServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM thirdServiceDate) DESC";
String GET_DURATION_COUNT_4TH_SERVICE = "select DATE_FORMAT(fourthServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals1 where fourthServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM fourthServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM fourthServiceDate) DESC";
String GET_DURATION_COUNT_5TH_SERVICE = "select DATE_FORMAT(fifthServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals1 where fifthServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM fifthServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM fifthServiceDate) DESC";
String GET_DURATION_COUNT_6TH_SERVICE = "select DATE_FORMAT(sixthServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals1 where sixthServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM sixthServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM sixthServiceDate) DESC";
String GET_DURATION_COUNT_7TH_SERVICE = "select DATE_FORMAT(seventhServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals1 where seventhServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM seventhServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM seventhServiceDate) DESC";
String GET_DURATION_COUNT_8TH_SERVICE = "select DATE_FORMAT(eigthServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT from customer_vehicle_actuals1 where eigthServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM eigthServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM eigthServiceDate) DESC";


String GET_DURATION_COUNT_COMPLETED_SERVICE = "SELECT DATE_FORMAT(ServiceDate, '%b%y') AS DURATION_CHOOSEN,COUNT(*) TOTAL_COUNT FROM servicedetails1 where ServiceDate BETWEEN SUBDATE(CURDATE(), INTERVAL 5 MONTH) AND NOW() GROUP BY EXTRACT(YEAR_MONTH FROM ServiceDate) ORDER BY EXTRACT(YEAR_MONTH FROM ServiceDate) DESC;";
 


}
